var PO_Module_Factory = function () {
  var PO = {
    name: 'PO',
    defaultElementNamespaceURI: 'http:\/\/colorexchangeformat.com\/CxF3-core',
    typeInfos: [{
        localName: 'ColorCIELCh',
        typeName: null,
        propertyInfos: [{
            name: 'l',
            required: true,
            elementName: 'L',
            typeInfo: 'Double'
          }, {
            name: 'c',
            required: true,
            elementName: 'C',
            typeInfo: 'Double'
          }, {
            name: 'h',
            required: true,
            elementName: 'H',
            typeInfo: 'Double'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'TagCollection',
        typeName: null,
        propertyInfos: [{
            name: 'tag',
            minOccurs: 0,
            collection: true,
            elementName: 'Tag',
            typeInfo: '.Tag'
          }, {
            name: 'name',
            required: true,
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CustomAttributeString',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            type: 'value'
          }, {
            name: 'label',
            required: true,
            attributeName: {
              localPart: 'Label'
            },
            type: 'attribute'
          }, {
            name: 'method',
            attributeName: {
              localPart: 'Method'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'Gloss',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            typeInfo: 'Double',
            type: 'value'
          }, {
            name: 'method',
            attributeName: {
              localPart: 'Method'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'DE94Type',
        propertyInfos: [{
            name: 'value',
            typeInfo: 'Double',
            type: 'value'
          }, {
            name: 'lRatio',
            required: true,
            typeInfo: 'Double',
            attributeName: {
              localPart: 'LRatio'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PrivateColorValues',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            typeInfo: 'Base64Binary',
            type: 'value'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'keyID',
            required: true,
            attributeName: {
              localPart: 'KeyID'
            },
            type: 'attribute'
          }, {
            name: 'measureDate',
            typeInfo: 'DateTime',
            attributeName: {
              localPart: 'MeasureDate'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'SingleAngleType',
        propertyInfos: [{
            name: 'singleAngleConfiguration',
            required: true,
            elementName: 'SingleAngleConfiguration',
            typeInfo: '.ESingleAngleConfigurationType'
          }, {
            name: 'illuminationAngle',
            required: true,
            elementName: 'IlluminationAngle',
            typeInfo: 'Double'
          }, {
            name: 'measurementAngle',
            required: true,
            elementName: 'MeasurementAngle',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'Tag',
        typeName: null,
        propertyInfos: [{
            name: 'name',
            required: true,
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'value',
            required: true,
            attributeName: {
              localPart: 'Value'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ColorCIELab',
        typeName: null,
        propertyInfos: [{
            name: 'l',
            required: true,
            elementName: 'L',
            typeInfo: 'Double'
          }, {
            name: 'a',
            required: true,
            elementName: 'A',
            typeInfo: 'Double'
          }, {
            name: 'b',
            required: true,
            elementName: 'B',
            typeInfo: 'Double'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'SubstrateType',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            typeInfo: '.ESubstrateType',
            type: 'value'
          }, {
            name: 'otherType',
            attributeName: {
              localPart: 'OtherType'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'DeviceFilterType',
        propertyInfos: [{
            name: 'value',
            typeInfo: '.EFilterType',
            type: 'value'
          }, {
            name: 'filterDescription',
            attributeName: {
              localPart: 'FilterDescription'
            },
            type: 'attribute'
          }, {
            name: 'filterPosition',
            typeInfo: 'Double',
            attributeName: {
              localPart: 'FilterPosition'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ColorCIExyY',
        typeName: null,
        propertyInfos: [{
            name: 'content',
            required: true,
            minOccurs: 3,
            maxOccurs: 3,
            collection: true,
            mixed: false,
            allowDom: false,
            elementTypeInfos: [{
                elementName: 'y',
                typeInfo: 'Double'
              }, {
                elementName: 'x',
                typeInfo: 'Double'
              }, {
                elementName: 'Y',
                typeInfo: 'Double'
              }],
            type: 'elementRefs'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ColorDensity',
        typeName: null,
        propertyInfos: [{
            name: 'density',
            required: true,
            elementName: 'Density',
            typeInfo: 'Double'
          }, {
            name: 'status',
            required: true,
            elementName: 'Status',
            typeInfo: '.EDensityStatusType'
          }, {
            name: 'filter',
            required: true,
            elementName: 'Filter',
            typeInfo: '.EDensityFilterType'
          }, {
            name: 'baseOffset',
            elementName: 'BaseOffset',
            typeInfo: 'Double'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ColorCMYKPlusN',
        typeName: null,
        propertyInfos: [{
            name: 'cyan',
            required: true,
            elementName: 'Cyan',
            typeInfo: 'Double'
          }, {
            name: 'magenta',
            required: true,
            elementName: 'Magenta',
            typeInfo: 'Double'
          }, {
            name: 'yellow',
            required: true,
            elementName: 'Yellow',
            typeInfo: 'Double'
          }, {
            name: 'black',
            required: true,
            elementName: 'Black',
            typeInfo: 'Double'
          }, {
            name: 'spotColor',
            minOccurs: 0,
            collection: true,
            elementName: 'SpotColor',
            typeInfo: '.SpotColorType'
          }, {
            name: 'profileSpecification',
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ProfileSpecification'
            },
            type: 'attribute'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ColorRecipe',
        typeName: null,
        propertyInfos: [{
            name: 'creationDate',
            required: true,
            elementName: 'CreationDate',
            typeInfo: 'DateTime'
          }, {
            name: 'tag',
            minOccurs: 0,
            collection: true,
            elementName: 'Tag',
            typeInfo: '.Tag'
          }, {
            name: 'substrate',
            elementName: 'Substrate'
          }, {
            name: 'process',
            elementName: 'Process'
          }, {
            name: 'colorant',
            required: true,
            collection: true,
            elementName: 'Colorant',
            typeInfo: '.Colorant'
          }, {
            name: 'units',
            required: true,
            attributeName: {
              localPart: 'Units'
            },
            type: 'attribute'
          }, {
            name: 'name',
            required: true,
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'comments',
            attributeName: {
              localPart: 'Comments'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'FinishType',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            typeInfo: '.EFinishType',
            type: 'value'
          }, {
            name: 'otherType',
            attributeName: {
              localPart: 'OtherType'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'Height',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            typeInfo: 'Double',
            type: 'value'
          }, {
            name: 'units',
            required: true,
            attributeName: {
              localPart: 'Units'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ProfileType.ProfileChoice.ProfileFile',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            typeInfo: 'Base64Binary',
            type: 'value'
          }, {
            name: 'profileName',
            attributeName: {
              localPart: 'ProfileName'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'Resources',
        typeName: null,
        propertyInfos: [{
            name: 'objectCollection',
            elementName: 'ObjectCollection',
            typeInfo: '.ObjectCollection'
          }, {
            name: 'colorSpecificationCollection',
            elementName: 'ColorSpecificationCollection',
            typeInfo: '.ColorSpecificationCollection'
          }, {
            name: 'profileCollection',
            elementName: 'ProfileCollection',
            typeInfo: '.ProfileCollection'
          }]
      }, {
        localName: 'CustomColorSpace',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            required: true,
            collection: true,
            elementName: 'Value',
            typeInfo: '.CustomDataType'
          }, {
            name: 'name',
            required: true,
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'MultiAngleType',
        propertyInfos: [{
            name: 'brdfAngle',
            required: true,
            collection: true,
            elementName: 'BRDFAngle',
            typeInfo: '.BRDFAngle'
          }]
      }, {
        localName: 'SpotColorType',
        propertyInfos: [{
            name: 'name',
            required: true,
            elementName: 'Name'
          }, {
            name: 'percentage',
            required: true,
            elementName: 'Percentage',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'ColorCIELuv',
        typeName: null,
        propertyInfos: [{
            name: 'l',
            required: true,
            elementName: 'L',
            typeInfo: 'Double'
          }, {
            name: 'u',
            required: true,
            elementName: 'U',
            typeInfo: 'Double'
          }, {
            name: 'v',
            required: true,
            elementName: 'V',
            typeInfo: 'Double'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ColorValues',
        typeName: null,
        propertyInfos: [{
            name: 'reflectanceSpectrumOrTransmittanceSpectrumOrEmissiveSpectrum',
            minOccurs: 0,
            collection: true,
            elementTypeInfos: [{
                elementName: 'ReflectanceSpectrum',
                typeInfo: '.ReflectanceSpectrum'
              }, {
                elementName: 'TransmittanceSpectrum',
                typeInfo: '.TransmittanceSpectrum'
              }, {
                elementName: 'EmissiveSpectrum',
                typeInfo: '.EmissiveSpectrum'
              }, {
                elementName: 'CustomSpectrum',
                typeInfo: '.CustomSpectrum'
              }, {
                elementName: 'ColorSRGB',
                typeInfo: '.ColorSRGB'
              }, {
                elementName: 'ColorAdobeRGB',
                typeInfo: '.ColorAdobeRGB'
              }, {
                elementName: 'ColorCIELab',
                typeInfo: '.ColorCIELab'
              }, {
                elementName: 'ColorCIELCh',
                typeInfo: '.ColorCIELCh'
              }, {
                elementName: 'ColorCIEXYZ',
                typeInfo: '.ColorCIEXYZ'
              }, {
                elementName: 'ColorEmissiveCIEXYZ',
                typeInfo: '.ColorEmissiveCIEXYZ'
              }, {
                elementName: 'ColorCIExyY',
                typeInfo: '.ColorCIExyY'
              }, {
                elementName: 'ColorEmissiveCIExyY',
                typeInfo: '.ColorEmissiveCIExyY'
              }, {
                elementName: 'ColorCIELuv',
                typeInfo: '.ColorCIELuv'
              }, {
                elementName: 'ColorDensity',
                typeInfo: '.ColorDensity'
              }, {
                elementName: 'PrivateSpectrum',
                typeInfo: '.PrivateSpectrum'
              }, {
                elementName: 'PrivateColorValues',
                typeInfo: '.PrivateColorValues'
              }, {
                elementName: 'CustomColorSpace',
                typeInfo: '.CustomColorSpace'
              }],
            type: 'elements'
          }]
      }, {
        localName: 'DEcmcType',
        propertyInfos: [{
            name: 'value',
            typeInfo: 'Double',
            type: 'value'
          }, {
            name: 'lRatio',
            required: true,
            typeInfo: 'Double',
            attributeName: {
              localPart: 'LRatio'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ColorHSL',
        typeName: null,
        propertyInfos: [{
            name: 'hue',
            required: true,
            elementName: 'Hue',
            typeInfo: 'Double'
          }, {
            name: 'saturation',
            required: true,
            elementName: 'Saturation',
            typeInfo: 'Double'
          }, {
            name: 'lightness',
            required: true,
            elementName: 'Lightness',
            typeInfo: 'Double'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ColorAdobeRGB',
        typeName: null,
        propertyInfos: [{
            name: 'maxRange',
            elementName: 'MaxRange',
            typeInfo: 'Short'
          }, {
            name: 'r',
            required: true,
            elementName: 'R',
            typeInfo: 'Short'
          }, {
            name: 'g',
            required: true,
            elementName: 'G',
            typeInfo: 'Short'
          }, {
            name: 'b',
            required: true,
            elementName: 'B',
            typeInfo: 'Short'
          }, {
            name: 'alpha',
            elementName: 'Alpha',
            typeInfo: 'Double'
          }, {
            name: 'profileSpecification',
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ProfileSpecification'
            },
            type: 'attribute'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'FileInformation',
        typeName: null,
        propertyInfos: [{
            name: 'creator',
            elementName: 'Creator'
          }, {
            name: 'creationDate',
            elementName: 'CreationDate',
            typeInfo: 'DateTime'
          }, {
            name: 'description',
            elementName: 'Description'
          }, {
            name: 'comment',
            elementName: 'Comment'
          }, {
            name: 'tag',
            minOccurs: 0,
            collection: true,
            elementName: 'Tag',
            typeInfo: '.Tag'
          }]
      }, {
        localName: 'ColorCMYK',
        typeName: null,
        propertyInfos: [{
            name: 'cyan',
            required: true,
            elementName: 'Cyan',
            typeInfo: 'Double'
          }, {
            name: 'magenta',
            required: true,
            elementName: 'Magenta',
            typeInfo: 'Double'
          }, {
            name: 'yellow',
            required: true,
            elementName: 'Yellow',
            typeInfo: 'Double'
          }, {
            name: 'black',
            required: true,
            elementName: 'Black',
            typeInfo: 'Double'
          }, {
            name: 'profileSpecification',
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ProfileSpecification'
            },
            type: 'attribute'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ColorNotation',
        typeName: null,
        propertyInfos: [{
            name: 'notation',
            required: true,
            attributeName: {
              localPart: 'Notation'
            },
            type: 'attribute'
          }, {
            name: 'name',
            required: true,
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ProfileType.Parameters',
        typeName: null,
        propertyInfos: [{
            name: 'name',
            required: true,
            elementName: 'Name'
          }, {
            name: 'valueChoice',
            required: true,
            elementName: 'ValueChoice',
            typeInfo: '.ProfileType.Parameters.ValueChoice'
          }]
      }, {
        localName: 'EmissiveSpectrum',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            typeInfo: {
              type: 'list',
              baseTypeInfo: 'Double'
            },
            type: 'value'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'measureDate',
            typeInfo: 'DateTime',
            attributeName: {
              localPart: 'MeasureDate'
            },
            type: 'attribute'
          }, {
            name: 'startWL',
            typeInfo: 'Short',
            attributeName: {
              localPart: 'StartWL'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'DeltaCustom',
        typeName: null,
        propertyInfos: [{
            name: 'deltaValue',
            minOccurs: 0,
            collection: true,
            elementName: 'DeltaValue',
            typeInfo: '.CustomDeltaType'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }, {
            name: 'standardRef',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'StandardRef'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ColorHTML',
        typeName: null,
        propertyInfos: [{
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'html',
            required: true,
            attributeName: {
              localPart: 'HTML'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ColorPantoneHexachrome',
        typeName: null,
        propertyInfos: [{
            name: 'cyan',
            required: true,
            elementName: 'Cyan',
            typeInfo: 'Double'
          }, {
            name: 'magenta',
            required: true,
            elementName: 'Magenta',
            typeInfo: 'Double'
          }, {
            name: 'yellow',
            required: true,
            elementName: 'Yellow',
            typeInfo: 'Double'
          }, {
            name: 'black',
            required: true,
            elementName: 'Black',
            typeInfo: 'Double'
          }, {
            name: 'orange',
            required: true,
            elementName: 'Orange',
            typeInfo: 'Double'
          }, {
            name: 'green',
            required: true,
            elementName: 'Green',
            typeInfo: 'Double'
          }, {
            name: 'profileSpecification',
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ProfileSpecification'
            },
            type: 'attribute'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CustomSpectrum',
        typeName: null,
        propertyInfos: [{
            name: 'spectralPoint',
            required: true,
            collection: true,
            elementName: 'SpectralPoint',
            typeInfo: '.SpectralPoint'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'measureDate',
            typeInfo: 'DateTime',
            attributeName: {
              localPart: 'MeasureDate'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CxF',
        typeName: null,
        propertyInfos: [{
            name: 'fileInformation',
            elementName: 'FileInformation',
            typeInfo: '.FileInformation'
          }, {
            name: 'resources',
            elementName: 'Resources',
            typeInfo: '.Resources'
          }, {
            name: 'customResources',
            elementName: 'CustomResources',
            typeInfo: '.CustomResources'
          }]
      }, {
        localName: 'CustomDeltaType',
        propertyInfos: [{
            name: 'value',
            typeInfo: 'Double',
            type: 'value'
          }, {
            name: 'label',
            required: true,
            attributeName: {
              localPart: 'Label'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CustomResources',
        typeName: null,
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'any',
            minOccurs: 0,
            collection: true,
            mixed: false,
            type: 'anyElement'
          }]
      }, {
        localName: 'CustomAttributeValue',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            typeInfo: 'Double',
            type: 'value'
          }, {
            name: 'label',
            required: true,
            attributeName: {
              localPart: 'Label'
            },
            type: 'attribute'
          }, {
            name: 'method',
            attributeName: {
              localPart: 'Method'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'DeviceIllumination',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            typeInfo: '.EDeviceIlluminationType',
            type: 'value'
          }, {
            name: 'customType',
            attributeName: {
              localPart: 'CustomType'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ProfileType',
        propertyInfos: [{
            name: 'profileChoice',
            required: true,
            elementName: 'ProfileChoice',
            typeInfo: '.ProfileType.ProfileChoice'
          }, {
            name: 'parameters',
            minOccurs: 0,
            collection: true,
            elementName: 'Parameters',
            typeInfo: '.ProfileType.Parameters'
          }, {
            name: 'created',
            elementName: 'Created',
            typeInfo: 'DateTime'
          }, {
            name: 'id',
            required: true,
            typeInfo: 'ID',
            attributeName: {
              localPart: 'Id'
            },
            type: 'attribute'
          }, {
            name: 'direction',
            required: true,
            values: ['Profile_Input', 'Profile_Output', 'Profile_Both'],
            attributeName: {
              localPart: 'Direction'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CustomDataType',
        propertyInfos: [{
            name: 'value',
            typeInfo: 'Double',
            type: 'value'
          }, {
            name: 'label',
            required: true,
            attributeName: {
              localPart: 'Label'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'Opacity',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            typeInfo: 'Double',
            type: 'value'
          }, {
            name: 'method',
            attributeName: {
              localPart: 'Method'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ProfileType.Parameters.ValueChoice',
        typeName: null,
        propertyInfos: [{
            name: 'doubleValue',
            required: true,
            elementName: 'DoubleValue',
            typeInfo: 'Double'
          }, {
            name: 'integerValue',
            required: true,
            elementName: 'IntegerValue',
            typeInfo: 'Int'
          }, {
            name: 'stringValue',
            required: true,
            elementName: 'StringValue'
          }]
      }, {
        localName: 'WavelengthRange',
        typeName: null,
        propertyInfos: [{
            name: 'startWL',
            required: true,
            typeInfo: 'Short',
            attributeName: {
              localPart: 'StartWL'
            },
            type: 'attribute'
          }, {
            name: 'increment',
            required: true,
            typeInfo: 'Short',
            attributeName: {
              localPart: 'Increment'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'GeometryChoiceType',
        propertyInfos: [{
            name: 'emissiveMode',
            required: true,
            elementName: 'EmissiveMode',
            typeInfo: '.EEmissiveModeType'
          }, {
            name: 'sphereGeometry',
            required: true,
            elementName: 'SphereGeometry',
            typeInfo: '.ESphereType'
          }, {
            name: 'singleAngle',
            required: true,
            elementName: 'SingleAngle',
            typeInfo: '.SingleAngleType'
          }, {
            name: 'unknownGeometry',
            required: true,
            elementName: 'UnknownGeometry'
          }, {
            name: 'multiAngle',
            required: true,
            elementName: 'MultiAngle',
            typeInfo: '.MultiAngleType'
          }]
      }, {
        localName: 'ColorEmissiveCIExyY',
        typeName: null,
        propertyInfos: [{
            name: 'content',
            required: true,
            minOccurs: 3,
            maxOccurs: 3,
            collection: true,
            mixed: false,
            allowDom: false,
            elementTypeInfos: [{
                elementName: 'x',
                typeInfo: 'Double'
              }, {
                elementName: 'Y',
                typeInfo: 'Double'
              }, {
                elementName: 'y',
                typeInfo: 'Double'
              }],
            type: 'elementRefs'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'DeviceColorValues',
        typeName: null,
        propertyInfos: [{
            name: 'colorHTMLOrColorNotationOrColorRGB',
            minOccurs: 0,
            collection: true,
            elementTypeInfos: [{
                elementName: 'ColorHTML',
                typeInfo: '.ColorHTML'
              }, {
                elementName: 'ColorNotation',
                typeInfo: '.ColorNotation'
              }, {
                elementName: 'ColorRGB',
                typeInfo: '.ColorRGB'
              }, {
                elementName: 'ColorHSL',
                typeInfo: '.ColorHSL'
              }, {
                elementName: 'ColorCMYK',
                typeInfo: '.ColorCMYK'
              }, {
                elementName: 'ColorCMYKPlusN',
                typeInfo: '.ColorCMYKPlusN'
              }, {
                elementName: 'ColorCustom',
                typeInfo: '.ColorCustom'
              }, {
                elementName: 'ColorPantoneHexachrome',
                typeInfo: '.ColorPantoneHexachrome'
              }, {
                elementName: 'ColorRecipe',
                typeInfo: '.ColorRecipe'
              }, {
                elementName: 'PrivateColorValues',
                typeInfo: '.PrivateColorValues'
              }],
            type: 'elements'
          }]
      }, {
        localName: 'ImageType',
        propertyInfos: [{
            name: 'value',
            typeInfo: 'Base64Binary',
            type: 'value'
          }, {
            name: 'label',
            attributeName: {
              localPart: 'Label'
            },
            type: 'attribute'
          }, {
            name: 'imageFileName',
            required: true,
            attributeName: {
              localPart: 'ImageFileName'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PhysicalAttributes',
        typeName: null,
        propertyInfos: [{
            name: 'targetType',
            elementName: 'TargetType',
            typeInfo: '.TargetType'
          }, {
            name: 'finishType',
            elementName: 'FinishType',
            typeInfo: '.FinishType'
          }, {
            name: 'substrateType',
            elementName: 'SubstrateType',
            typeInfo: '.SubstrateType'
          }, {
            name: 'quantity',
            elementName: 'Quantity',
            typeInfo: '.Quantity'
          }, {
            name: 'height',
            elementName: 'Height',
            typeInfo: '.Height'
          }, {
            name: 'width',
            elementName: 'Width',
            typeInfo: '.Width'
          }, {
            name: 'length',
            elementName: 'Length',
            typeInfo: '.Length'
          }, {
            name: 'thickness',
            elementName: 'Thickness',
            typeInfo: '.Thickness'
          }, {
            name: 'gloss',
            minOccurs: 0,
            collection: true,
            elementName: 'Gloss',
            typeInfo: '.Gloss'
          }, {
            name: 'opacity',
            minOccurs: 0,
            collection: true,
            elementName: 'Opacity',
            typeInfo: '.Opacity'
          }, {
            name: 'customAttributeString',
            minOccurs: 0,
            collection: true,
            elementName: 'CustomAttributeString',
            typeInfo: '.CustomAttributeString'
          }, {
            name: 'customAttributeValue',
            minOccurs: 0,
            collection: true,
            elementName: 'CustomAttributeValue',
            typeInfo: '.CustomAttributeValue'
          }, {
            name: 'image',
            minOccurs: 0,
            collection: true,
            elementName: 'Image',
            typeInfo: '.ImageType'
          }]
      }, {
        localName: 'DeltaCIELab',
        typeName: null,
        propertyInfos: [{
            name: 'dl',
            elementName: 'dL',
            typeInfo: 'Double'
          }, {
            name: 'da',
            elementName: 'dA',
            typeInfo: 'Double'
          }, {
            name: 'db',
            elementName: 'dB',
            typeInfo: 'Double'
          }, {
            name: 'dc',
            elementName: 'dC',
            typeInfo: 'Double'
          }, {
            name: 'dh',
            elementName: 'dH',
            typeInfo: 'Double'
          }, {
            name: 'de',
            elementName: 'dE',
            typeInfo: 'Double'
          }, {
            name: 'dEcmc',
            typeInfo: '.DEcmcType'
          }, {
            name: 'de94',
            elementName: 'dE94',
            typeInfo: '.DE94Type'
          }, {
            name: 'de2000',
            elementName: 'dE2000',
            typeInfo: '.DE2000Type'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }, {
            name: 'standardRef',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'StandardRef'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ColorCIEXYZ',
        typeName: null,
        propertyInfos: [{
            name: 'x',
            required: true,
            elementName: 'X',
            typeInfo: 'Double'
          }, {
            name: 'y',
            required: true,
            elementName: 'Y',
            typeInfo: 'Double'
          }, {
            name: 'z',
            required: true,
            elementName: 'Z',
            typeInfo: 'Double'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ColorCustom',
        typeName: null,
        propertyInfos: [{
            name: 'spotColor',
            required: true,
            collection: true,
            elementName: 'SpotColor',
            typeInfo: '.SpotColorType'
          }, {
            name: 'profileSpecification',
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ProfileSpecification'
            },
            type: 'attribute'
          }, {
            name: 'name',
            required: true,
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ColorDifferenceValues',
        typeName: null,
        propertyInfos: [{
            name: 'deltaCIELabOrDeltaCustom',
            minOccurs: 0,
            collection: true,
            elementTypeInfos: [{
                elementName: 'DeltaCIELab',
                typeInfo: '.DeltaCIELab'
              }, {
                elementName: 'DeltaCustom',
                typeInfo: '.DeltaCustom'
              }],
            type: 'elements'
          }]
      }, {
        localName: 'ProfileType.ProfileChoice',
        typeName: null,
        propertyInfos: [{
            name: 'profileFile',
            required: true,
            elementName: 'ProfileFile',
            typeInfo: '.ProfileType.ProfileChoice.ProfileFile'
          }, {
            name: 'profileURI',
            required: true,
            elementName: 'ProfileURI'
          }]
      }, {
        localName: 'Device',
        typeName: null,
        propertyInfos: [{
            name: 'manufacturer',
            elementName: 'Manufacturer'
          }, {
            name: 'model',
            elementName: 'Model'
          }, {
            name: 'serialNumber',
            elementName: 'SerialNumber'
          }, {
            name: 'deviceClass',
            elementName: 'DeviceClass',
            typeInfo: '.EDeviceClassType'
          }, {
            name: 'deviceFilter',
            elementName: 'DeviceFilter',
            typeInfo: '.DeviceFilterType'
          }, {
            name: 'deviceIllumination',
            elementName: 'DeviceIllumination',
            typeInfo: '.DeviceIllumination'
          }, {
            name: 'devicePolarization',
            elementName: 'DevicePolarization',
            typeInfo: 'Boolean'
          }]
      }, {
        localName: 'Colorant',
        typeName: null,
        propertyInfos: [{
            name: 'partNumber',
            elementName: 'PartNumber'
          }, {
            name: 'density',
            mixed: false,
            allowDom: false,
            elementName: 'Density',
            typeInfo: 'Double',
            type: 'elementRef'
          }, {
            name: 'value',
            required: true,
            elementName: 'Value',
            typeInfo: 'Double'
          }, {
            name: 'name',
            required: true,
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'id',
            attributeName: {
              localPart: 'ID'
            },
            type: 'attribute'
          }, {
            name: 'isBase',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'isBase'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ColorSpecification',
        typeName: null,
        propertyInfos: [{
            name: 'tristimulusSpec',
            elementName: 'TristimulusSpec',
            typeInfo: '.TristimulusSpec'
          }, {
            name: 'measurementSpec',
            required: true,
            elementName: 'MeasurementSpec',
            typeInfo: '.MeasurementSpec'
          }, {
            name: 'physicalAttributes',
            elementName: 'PhysicalAttributes',
            typeInfo: '.PhysicalAttributes'
          }, {
            name: 'id',
            required: true,
            typeInfo: 'ID',
            attributeName: {
              localPart: 'Id'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ProfileCollection',
        typeName: null,
        propertyInfos: [{
            name: 'profile',
            minOccurs: 0,
            collection: true,
            elementName: 'Profile',
            typeInfo: '.ProfileType'
          }]
      }, {
        localName: 'GeometryChoice',
        typeName: null,
        baseTypeInfo: '.GeometryChoiceType'
      }, {
        localName: 'Thickness',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            typeInfo: 'Double',
            type: 'value'
          }, {
            name: 'units',
            required: true,
            attributeName: {
              localPart: 'Units'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ColorSRGB',
        typeName: null,
        propertyInfos: [{
            name: 'maxRange',
            elementName: 'MaxRange',
            typeInfo: 'Short'
          }, {
            name: 'r',
            required: true,
            elementName: 'R',
            typeInfo: 'Short'
          }, {
            name: 'g',
            required: true,
            elementName: 'G',
            typeInfo: 'Short'
          }, {
            name: 'b',
            required: true,
            elementName: 'B',
            typeInfo: 'Short'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'BRDFAngle',
        typeName: null,
        propertyInfos: [{
            name: 'illuminationAngle',
            required: true,
            elementName: 'IlluminationAngle',
            typeInfo: 'Double'
          }, {
            name: 'aspecular',
            required: true,
            elementName: 'Aspecular',
            typeInfo: 'Double'
          }, {
            name: 'azimuth',
            elementName: 'Azimuth',
            typeInfo: 'Double'
          }, {
            name: 'notation',
            required: true,
            attributeName: {
              localPart: 'Notation'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'Illuminant',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            values: ['A', 'B', 'C', 'D50', 'D55', 'D60', 'D65', 'D75', 'E', 'F2', 'F3', 'F7', 'F9', 'F10', 'F11', 'F12', '9300', 'TL84', 'TL83', 'UL30', 'UL35', 'UL50', 'Custom'],
            type: 'value'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'x',
            typeInfo: 'Double',
            attributeName: {
              localPart: 'X'
            },
            type: 'attribute'
          }, {
            name: 'y',
            typeInfo: 'Double',
            attributeName: {
              localPart: 'Y'
            },
            type: 'attribute'
          }, {
            name: 'z',
            typeInfo: 'Double',
            attributeName: {
              localPart: 'Z'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ObjectCollection',
        typeName: null,
        propertyInfos: [{
            name: 'object',
            required: true,
            collection: true,
            elementName: 'Object',
            typeInfo: '.Object'
          }]
      }, {
        localName: 'ColorEmissiveCIEXYZ',
        typeName: null,
        propertyInfos: [{
            name: 'x',
            required: true,
            elementName: 'X',
            typeInfo: 'Double'
          }, {
            name: 'y',
            required: true,
            elementName: 'Y',
            typeInfo: 'Double'
          }, {
            name: 'z',
            required: true,
            elementName: 'Z',
            typeInfo: 'Double'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CustomIlluminant',
        typeName: null,
        propertyInfos: [{
            name: 'spdList',
            elementName: 'SPDList',
            typeInfo: {
              type: 'list',
              baseTypeInfo: 'Double'
            }
          }, {
            name: 'spectralPoint',
            minOccurs: 0,
            collection: true,
            elementName: 'SpectralPoint',
            typeInfo: '.SpectralPoint'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'wlStart',
            typeInfo: 'Short',
            attributeName: {
              localPart: 'WLStart'
            },
            type: 'attribute'
          }, {
            name: 'listIncrement',
            typeInfo: 'Short',
            attributeName: {
              localPart: 'List_Increment'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'Object',
        typeName: null,
        propertyInfos: [{
            name: 'creationDate',
            required: true,
            elementName: 'CreationDate',
            typeInfo: 'DateTime'
          }, {
            name: 'comment',
            elementName: 'Comment'
          }, {
            name: 'colorValues',
            elementName: 'ColorValues',
            typeInfo: '.ColorValues'
          }, {
            name: 'colorDifferenceValues',
            elementName: 'ColorDifferenceValues',
            typeInfo: '.ColorDifferenceValues'
          }, {
            name: 'deviceColorValues',
            elementName: 'DeviceColorValues',
            typeInfo: '.DeviceColorValues'
          }, {
            name: 'tagCollection',
            minOccurs: 0,
            collection: true,
            elementName: 'TagCollection',
            typeInfo: '.TagCollection'
          }, {
            name: 'physicalAttributes',
            elementName: 'PhysicalAttributes',
            typeInfo: '.PhysicalAttributes'
          }, {
            name: 'objectType',
            required: true,
            attributeName: {
              localPart: 'ObjectType'
            },
            type: 'attribute'
          }, {
            name: 'name',
            required: true,
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'id',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'Id'
            },
            type: 'attribute'
          }, {
            name: 'guid',
            attributeName: {
              localPart: 'GUID'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'Width',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            typeInfo: 'Double',
            type: 'value'
          }, {
            name: 'units',
            required: true,
            attributeName: {
              localPart: 'Units'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'MeasurementSpec',
        typeName: null,
        propertyInfos: [{
            name: 'measurementType',
            required: true,
            elementName: 'MeasurementType',
            typeInfo: '.ESpectrumType'
          }, {
            name: 'geometryChoice',
            required: true,
            elementName: 'GeometryChoice',
            typeInfo: '.GeometryChoice'
          }, {
            name: 'wavelengthRange',
            elementName: 'WavelengthRange',
            typeInfo: '.WavelengthRange'
          }, {
            name: 'luminanceUnitsType',
            elementName: 'LuminanceUnitsType',
            typeInfo: '.ELuminanceUnits'
          }, {
            name: 'calibrationStandard',
            elementName: 'CalibrationStandard'
          }, {
            name: 'aperture',
            elementName: 'Aperture'
          }, {
            name: 'backing',
            elementName: 'Backing'
          }, {
            name: 'bandpassCorrected',
            elementName: 'BandpassCorrected',
            typeInfo: 'Boolean'
          }, {
            name: 'device',
            elementName: 'Device',
            typeInfo: '.Device'
          }]
      }, {
        localName: 'DE2000Type',
        propertyInfos: [{
            name: 'value',
            typeInfo: 'Double',
            type: 'value'
          }, {
            name: 'lRatio',
            required: true,
            typeInfo: 'Double',
            attributeName: {
              localPart: 'LRatio'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'TargetType',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            typeInfo: '.ETargetType',
            type: 'value'
          }, {
            name: 'otherType',
            attributeName: {
              localPart: 'OtherType'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ColorSpecificationCollection',
        typeName: null,
        propertyInfos: [{
            name: 'colorSpecification',
            required: true,
            collection: true,
            elementName: 'ColorSpecification',
            typeInfo: '.ColorSpecification'
          }]
      }, {
        localName: 'SpectralPoint',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            typeInfo: 'Double',
            type: 'value'
          }, {
            name: 'wl',
            required: true,
            typeInfo: 'Double',
            attributeName: {
              localPart: 'WL'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'TransmittanceSpectrum',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            typeInfo: {
              type: 'list',
              baseTypeInfo: 'Double'
            },
            type: 'value'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'measureDate',
            typeInfo: 'DateTime',
            attributeName: {
              localPart: 'MeasureDate'
            },
            type: 'attribute'
          }, {
            name: 'startWL',
            typeInfo: 'Short',
            attributeName: {
              localPart: 'StartWL'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ColorRGB',
        typeName: null,
        propertyInfos: [{
            name: 'maxRange',
            elementName: 'MaxRange',
            typeInfo: 'Short'
          }, {
            name: 'r',
            required: true,
            elementName: 'R',
            typeInfo: 'Short'
          }, {
            name: 'g',
            required: true,
            elementName: 'G',
            typeInfo: 'Short'
          }, {
            name: 'b',
            required: true,
            elementName: 'B',
            typeInfo: 'Short'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }, {
            name: 'profileSpecification',
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ProfileSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'Quantity',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            typeInfo: 'Double',
            type: 'value'
          }, {
            name: 'units',
            attributeName: {
              localPart: 'Units'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'Length',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            typeInfo: 'Double',
            type: 'value'
          }, {
            name: 'units',
            required: true,
            attributeName: {
              localPart: 'Units'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'Observer',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            values: ['2_Degree', '10_Degree', 'Custom_CMF'],
            type: 'value'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'angle',
            typeInfo: 'Short',
            attributeName: {
              localPart: 'Angle'
            },
            type: 'attribute'
          }, {
            name: 'age',
            typeInfo: 'Short',
            attributeName: {
              localPart: 'Age'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PrivateSpectrum',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            typeInfo: 'Base64Binary',
            type: 'value'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'keyID',
            required: true,
            attributeName: {
              localPart: 'KeyID'
            },
            type: 'attribute'
          }, {
            name: 'measureDate',
            typeInfo: 'DateTime',
            attributeName: {
              localPart: 'MeasureDate'
            },
            type: 'attribute'
          }, {
            name: 'startWL',
            typeInfo: 'Short',
            attributeName: {
              localPart: 'StartWL'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ReflectanceSpectrum',
        typeName: null,
        propertyInfos: [{
            name: 'value',
            typeInfo: {
              type: 'list',
              baseTypeInfo: 'Double'
            },
            type: 'value'
          }, {
            name: 'name',
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'measureDate',
            typeInfo: 'DateTime',
            attributeName: {
              localPart: 'MeasureDate'
            },
            type: 'attribute'
          }, {
            name: 'startWL',
            typeInfo: 'Short',
            attributeName: {
              localPart: 'StartWL'
            },
            type: 'attribute'
          }, {
            name: 'colorSpecification',
            required: true,
            typeInfo: 'NCName',
            attributeName: {
              localPart: 'ColorSpecification'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'SerialNumber',
        typeName: null
      }, {
        localName: 'TristimulusSpec',
        typeName: null,
        propertyInfos: [{
            name: 'illuminant',
            required: true,
            elementName: 'Illuminant',
            typeInfo: '.Illuminant'
          }, {
            name: 'customIlluminant',
            required: true,
            elementName: 'CustomIlluminant',
            typeInfo: '.CustomIlluminant'
          }, {
            name: 'observer',
            required: true,
            elementName: 'Observer',
            typeInfo: '.Observer'
          }, {
            name: 'method',
            required: true,
            elementName: 'Method',
            typeInfo: '.EAstmTableType'
          }]
      }, {
        type: 'enumInfo',
        localName: 'ESpectrumType',
        values: ['Spectrum_Reflectance', 'Spectrum_Transmittance', 'Spectrum_TotalTransmittance', 'Spectrum_Emissive', 'Colorimetric_Reflectance', 'Colorimetric_Transmittance', 'Colorimetric_Emissive', 'Spectrum_Custom']
      }, {
        type: 'enumInfo',
        localName: 'EFinishType',
        values: ['Coated', 'Uncoated', 'Matte', 'Polished', 'Glossy', 'Satin', 'Other']
      }, {
        type: 'enumInfo',
        localName: 'ESubstrateType',
        values: ['Film', 'Leather', 'Metal', 'Paint', 'Paper', 'Plastic', 'Textile', 'Tile', 'Vinyl', 'Wood', 'Other']
      }, {
        type: 'enumInfo',
        localName: 'EDeviceClassType',
        values: ['DeviceClass_Spot', 'DeviceClass_Scanning', 'DeviceClass_Other']
      }, {
        type: 'enumInfo',
        localName: 'EDensityFilterType',
        values: ['Visual', 'Cyan', 'Magenta', 'Yellow', 'Black', 'Red', 'Green', 'Blue', 'A', 'B']
      }, {
        type: 'enumInfo',
        localName: 'EDensityStatusType',
        values: ['A', 'E', 'I', 'M', 'T', 'SpectralX', 'Spectral', 'HiFi', 'Hex', 'Txp', 'Ex', 'DIN', 'DIN-NB', 'PD', 'APD']
      }, {
        type: 'enumInfo',
        localName: 'EFilterType',
        values: ['Filter_None', 'Filter_UVExcluded', 'Filter_UVD65', 'Filter_Partial', 'Filter_Custom']
      }, {
        type: 'enumInfo',
        localName: 'EAstmTableType',
        values: ['E308_Table5', 'E308_Table6', 'E308_1nm', 'unknown']
      }, {
        type: 'enumInfo',
        localName: 'EEmissiveModeType',
        values: ['EmissiveMode_Diffuser', 'EmissiveMode_Reflected', 'EmissiveMode_Other']
      }, {
        type: 'enumInfo',
        localName: 'ELuminanceUnits',
        values: ['normalized', 'fL', 'cd\/ft2', 'cd\/m2']
      }, {
        type: 'enumInfo',
        localName: 'ESingleAngleConfigurationType',
        values: ['Annular', 'Uniplanar']
      }, {
        type: 'enumInfo',
        localName: 'EDeviceIlluminationType',
        values: ['M0_Incandescent', 'M1_Daylight', 'M2_UVExcluded', 'M3_Polarized', 'Flash', 'LED', 'Ambient', 'Custom']
      }, {
        type: 'enumInfo',
        localName: 'ETargetType',
        values: ['IT8.7\/1', 'IT8.7\/2', 'IT8.7\/3', 'IT8.7\/4', 'ECI2002', 'Other']
      }, {
        type: 'enumInfo',
        localName: 'ESphereType',
        values: ['Specular_Included', 'Specular_Excluded', 'Diffuse']
      }],
    elementInfos: [{
        typeInfo: '.Colorant',
        elementName: 'Colorant'
      }, {
        typeInfo: '.PhysicalAttributes',
        elementName: 'PhysicalAttributes'
      }, {
        typeInfo: '.ELuminanceUnits',
        elementName: 'LuminanceUnitsType'
      }, {
        typeInfo: '.Resources',
        elementName: 'Resources'
      }, {
        typeInfo: '.CustomIlluminant',
        elementName: 'CustomIlluminant'
      }, {
        typeInfo: '.PrivateSpectrum',
        elementName: 'PrivateSpectrum'
      }, {
        typeInfo: '.CxF',
        elementName: 'CxF'
      }, {
        typeInfo: '.ColorDifferenceValues',
        elementName: 'ColorDifferenceValues'
      }, {
        elementName: 'Process'
      }, {
        typeInfo: '.Width',
        elementName: 'Width'
      }, {
        typeInfo: '.TagCollection',
        elementName: 'TagCollection'
      }, {
        typeInfo: 'Double',
        elementName: 'x',
        scope: '.ColorEmissiveCIExyY'
      }, {
        elementName: 'Substrate'
      }, {
        typeInfo: '.SubstrateType',
        elementName: 'SubstrateType'
      }, {
        typeInfo: '.Opacity',
        elementName: 'Opacity'
      }, {
        typeInfo: '.ColorCIExyY',
        elementName: 'ColorCIExyY'
      }, {
        typeInfo: '.ColorCMYKPlusN',
        elementName: 'ColorCMYKPlusN'
      }, {
        typeInfo: '.EAstmTableType',
        elementName: 'Method'
      }, {
        typeInfo: '.TransmittanceSpectrum',
        elementName: 'TransmittanceSpectrum'
      }, {
        typeInfo: 'Double',
        elementName: 'Density',
        scope: '.Colorant'
      }, {
        typeInfo: '.ColorCIELCh',
        elementName: 'ColorCIELCh'
      }, {
        typeInfo: '.TristimulusSpec',
        elementName: 'TristimulusSpec'
      }, {
        typeInfo: '.Observer',
        elementName: 'Observer'
      }, {
        typeInfo: '.ColorHTML',
        elementName: 'ColorHTML'
      }, {
        typeInfo: '.Object',
        elementName: 'Object'
      }, {
        typeInfo: '.CustomColorSpace',
        elementName: 'CustomColorSpace'
      }, {
        typeInfo: '.CustomAttributeValue',
        elementName: 'CustomAttributeValue'
      }, {
        typeInfo: '.ESpectrumType',
        elementName: 'MeasurementType'
      }, {
        typeInfo: '.DeltaCIELab',
        elementName: 'DeltaCIELab'
      }, {
        typeInfo: '.CustomAttributeString',
        elementName: 'CustomAttributeString'
      }, {
        typeInfo: '.ColorSpecification',
        elementName: 'ColorSpecification'
      }, {
        typeInfo: '.DeviceFilterType',
        elementName: 'DeviceFilter'
      }, {
        typeInfo: '.Gloss',
        elementName: 'Gloss'
      }, {
        typeInfo: '.MeasurementSpec',
        elementName: 'MeasurementSpec'
      }, {
        typeInfo: '.EDeviceClassType',
        elementName: 'DeviceClass'
      }, {
        typeInfo: '.SerialNumber',
        elementName: 'SerialNumber'
      }, {
        typeInfo: '.ColorCIEXYZ',
        elementName: 'ColorCIEXYZ'
      }, {
        typeInfo: '.ReflectanceSpectrum',
        elementName: 'ReflectanceSpectrum'
      }, {
        typeInfo: '.ColorValues',
        elementName: 'ColorValues'
      }, {
        typeInfo: '.ColorSRGB',
        elementName: 'ColorSRGB'
      }, {
        typeInfo: '.ColorHSL',
        elementName: 'ColorHSL'
      }, {
        typeInfo: 'DateTime',
        elementName: 'CreationDate'
      }, {
        typeInfo: 'Double',
        elementName: 'Y',
        scope: '.ColorEmissiveCIExyY'
      }, {
        typeInfo: '.FileInformation',
        elementName: 'FileInformation'
      }, {
        typeInfo: '.ProfileType',
        elementName: 'Profile'
      }, {
        typeInfo: '.ColorEmissiveCIExyY',
        elementName: 'ColorEmissiveCIExyY'
      }, {
        typeInfo: '.PrivateColorValues',
        elementName: 'PrivateColorValues'
      }, {
        typeInfo: '.ColorEmissiveCIEXYZ',
        elementName: 'ColorEmissiveCIEXYZ'
      }, {
        typeInfo: '.ImageType',
        elementName: 'Image'
      }, {
        typeInfo: '.ColorAdobeRGB',
        elementName: 'ColorAdobeRGB'
      }, {
        typeInfo: '.Tag',
        elementName: 'Tag'
      }, {
        typeInfo: '.Height',
        elementName: 'Height'
      }, {
        typeInfo: '.Device',
        elementName: 'Device'
      }, {
        typeInfo: 'Double',
        elementName: 'y',
        scope: '.ColorCIExyY'
      }, {
        typeInfo: '.ObjectCollection',
        elementName: 'ObjectCollection'
      }, {
        typeInfo: '.ColorCIELuv',
        elementName: 'ColorCIELuv'
      }, {
        typeInfo: '.EmissiveSpectrum',
        elementName: 'EmissiveSpectrum'
      }, {
        typeInfo: '.ColorCMYK',
        elementName: 'ColorCMYK'
      }, {
        typeInfo: '.ESingleAngleConfigurationType',
        elementName: 'SingleAngleConfiguration'
      }, {
        typeInfo: '.ColorCIELab',
        elementName: 'ColorCIELab'
      }, {
        typeInfo: '.ColorSpecificationCollection',
        elementName: 'ColorSpecificationCollection'
      }, {
        typeInfo: 'Double',
        elementName: 'Y',
        scope: '.ColorCIExyY'
      }, {
        typeInfo: '.DeviceColorValues',
        elementName: 'DeviceColorValues'
      }, {
        typeInfo: 'Double',
        elementName: 'x',
        scope: '.ColorCIExyY'
      }, {
        typeInfo: '.ColorNotation',
        elementName: 'ColorNotation'
      }, {
        typeInfo: '.TargetType',
        elementName: 'TargetType'
      }, {
        typeInfo: 'Double',
        elementName: 'y',
        scope: '.ColorEmissiveCIExyY'
      }, {
        typeInfo: '.SpotColorType',
        elementName: 'SpotColor'
      }, {
        typeInfo: '.DeltaCustom',
        elementName: 'DeltaCustom'
      }, {
        typeInfo: '.ProfileCollection',
        elementName: 'ProfileCollection'
      }, {
        typeInfo: '.CustomSpectrum',
        elementName: 'CustomSpectrum'
      }, {
        typeInfo: '.ColorCustom',
        elementName: 'ColorCustom'
      }, {
        typeInfo: '.ColorPantoneHexachrome',
        elementName: 'ColorPantoneHexachrome'
      }, {
        typeInfo: '.GeometryChoice',
        elementName: 'GeometryChoice'
      }, {
        typeInfo: '.FinishType',
        elementName: 'FinishType'
      }, {
        typeInfo: '.Illuminant',
        elementName: 'Illuminant'
      }, {
        typeInfo: '.ColorRecipe',
        elementName: 'ColorRecipe'
      }, {
        typeInfo: '.CustomResources',
        elementName: 'CustomResources'
      }, {
        typeInfo: '.DeviceIllumination',
        elementName: 'DeviceIllumination'
      }, {
        typeInfo: '.Length',
        elementName: 'Length'
      }, {
        typeInfo: '.ColorDensity',
        elementName: 'ColorDensity'
      }, {
        typeInfo: '.Quantity',
        elementName: 'Quantity'
      }, {
        typeInfo: '.BRDFAngle',
        elementName: 'BRDFAngle'
      }, {
        typeInfo: '.WavelengthRange',
        elementName: 'WavelengthRange'
      }, {
        typeInfo: '.ColorRGB',
        elementName: 'ColorRGB'
      }, {
        typeInfo: '.SpectralPoint',
        elementName: 'SpectralPoint'
      }, {
        typeInfo: '.Thickness',
        elementName: 'Thickness'
      }]
  };
  return {
    PO: PO
  };
};
if (typeof define === 'function' && define.amd) {
  define([], PO_Module_Factory);
}
else {
  var PO_Module = PO_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.PO = PO_Module.PO;
  }
  else {
    var PO = PO_Module.PO;
  }
}