# generated by datamodel-codegen:
#   filename:  PO.jsonschema
#   timestamp: 2025-03-10T15:33:35+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

from .. import AnyURI
from .. import Parameters as Parameters_1
from .. import ProfileChoice as ProfileChoice_1
from .. import String


class ProfileChoice(BaseModel):
    profileFile: ProfileChoice_1.ProfileFile = Field(..., title='profileFile')
    profileURI: AnyURI = Field(..., title='profileURI')


class Parameters(BaseModel):
    name: Optional[String] = Field(..., title='name')
    valueChoice: Parameters_1.ValueChoice = Field(..., title='valueChoice')
