# generated by datamodel-codegen:
#   filename:  PO.jsonschema
#   timestamp: 2025-03-10T15:33:35+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

from .. import Double, Int, String


class ValueChoice(BaseModel):
    doubleValue: Optional[Double] = Field(..., title='doubleValue')
    integerValue: Int = Field(..., title='integerValue')
    stringValue: Optional[String] = Field(..., title='stringValue')
