# generated by datamodel-codegen:
#   filename:  PO.jsonschema
#   timestamp: 2025-03-10T15:33:35+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

from .. import Base64Binary, String


class ProfileFile(BaseModel):
    value: Optional[Base64Binary] = Field(None, title='value')
    profileName: Optional[String] = Field(None, title='profileName')
