"""This file was generated by xsdata, v25.4, on 2025-05-21 12:08:38

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass, field

from colour_cxf.cxf3.edensity_filter_type import EdensityFilterType
from colour_cxf.cxf3.edensity_status_type import EdensityStatusType

__NAMESPACE__ = "http://colorexchangeformat.com/CxF3-core"


@dataclass
class ColorDensity:
    """Color Value Type used to represent a particular density status and filter.

    If specified as a relative density value, an optional BaseOffset may
    be given with the density values that were subtracted in order to
    get media-relative units.
    """

    class Meta:
        namespace = "http://colorexchangeformat.com/CxF3-core"

    density: float | None = field(
        default=None,
        metadata={
            "name": "Density",
            "type": "Element",
            "required": True,
        },
    )
    status: EdensityStatusType | None = field(
        default=None,
        metadata={
            "name": "Status",
            "type": "Element",
            "required": True,
        },
    )
    filter: EdensityFilterType | None = field(
        default=None,
        metadata={
            "name": "Filter",
            "type": "Element",
            "required": True,
        },
    )
    base_offset: float | None = field(
        default=None,
        metadata={
            "name": "BaseOffset",
            "type": "Element",
        },
    )
    name: str | None = field(
        default=None,
        metadata={
            "name": "Name",
            "type": "Attribute",
        },
    )
    color_specification: str | None = field(
        default=None,
        metadata={
            "name": "ColorSpecification",
            "type": "Attribute",
            "required": True,
        },
    )
