"""This file was generated by xsdata, v25.4, on 2025-05-21 12:08:38

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass, field

__NAMESPACE__ = "http://colorexchangeformat.com/CxF3-core"


@dataclass
class ColorSrgb:
    """
    Device independent colorspace of RGB values for D65 2 degree observer.

    Parameters
    ----------
    max_range
        Optional parameter which defines the maximum range of values
        represented if based on values other than usual. For instance, RGB
        values for monitor display are typically between 0-255, but higher
        resolutions are possible.
    r
    g
    b
    name
    color_specification
    """

    class Meta:
        name = "ColorSRGB"
        namespace = "http://colorexchangeformat.com/CxF3-core"

    max_range: int | None = field(
        default=None,
        metadata={
            "name": "MaxRange",
            "type": "Element",
        },
    )
    r: int | None = field(
        default=None,
        metadata={
            "name": "R",
            "type": "Element",
            "required": True,
        },
    )
    g: int | None = field(
        default=None,
        metadata={
            "name": "G",
            "type": "Element",
            "required": True,
        },
    )
    b: int | None = field(
        default=None,
        metadata={
            "name": "B",
            "type": "Element",
            "required": True,
        },
    )
    name: str | None = field(
        default=None,
        metadata={
            "name": "Name",
            "type": "Attribute",
        },
    )
    color_specification: str | None = field(
        default=None,
        metadata={
            "name": "ColorSpecification",
            "type": "Attribute",
            "required": True,
        },
    )
