"""This file was generated by xsdata, v25.4, on 2025-05-21 12:08:38

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass, field

from colour_cxf.cxf3.de94_type import De94Type
from colour_cxf.cxf3.de2000_type import De2000Type
from colour_cxf.cxf3.decmc_type import DecmcType

__NAMESPACE__ = "http://colorexchangeformat.com/CxF3-core"


@dataclass
class DeltaCielab:
    """
    Color Difference type that holds CIELab color difference (Delta) values.
    """

    class Meta:
        name = "DeltaCIELab"
        namespace = "http://colorexchangeformat.com/CxF3-core"

    d_l: float | None = field(
        default=None,
        metadata={
            "name": "dL",
            "type": "Element",
        },
    )
    d_a: float | None = field(
        default=None,
        metadata={
            "name": "dA",
            "type": "Element",
        },
    )
    d_b: float | None = field(
        default=None,
        metadata={
            "name": "dB",
            "type": "Element",
        },
    )
    d_c: float | None = field(
        default=None,
        metadata={
            "name": "dC",
            "type": "Element",
        },
    )
    d_h: float | None = field(
        default=None,
        metadata={
            "name": "dH",
            "type": "Element",
        },
    )
    d_e: float | None = field(
        default=None,
        metadata={
            "name": "dE",
            "type": "Element",
        },
    )
    d_ecmc: DecmcType | None = field(
        default=None,
        metadata={
            "name": "dEcmc",
            "type": "Element",
        },
    )
    d_e94: De94Type | None = field(
        default=None,
        metadata={
            "name": "dE94",
            "type": "Element",
        },
    )
    d_e2000: De2000Type | None = field(
        default=None,
        metadata={
            "name": "dE2000",
            "type": "Element",
        },
    )
    name: str | None = field(
        default=None,
        metadata={
            "name": "Name",
            "type": "Attribute",
        },
    )
    color_specification: str | None = field(
        default=None,
        metadata={
            "name": "ColorSpecification",
            "type": "Attribute",
            "required": True,
        },
    )
    standard_ref: str | None = field(
        default=None,
        metadata={
            "name": "StandardRef",
            "type": "Attribute",
            "required": True,
        },
    )
