"""This file was generated by xsdata, v25.4, on 2025-05-21 12:08:38

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass, field

from colour_cxf.cxf3.device_class import DeviceClass
from colour_cxf.cxf3.device_filter import DeviceFilter
from colour_cxf.cxf3.device_illumination import DeviceIllumination

__NAMESPACE__ = "http://colorexchangeformat.com/CxF3-core"


@dataclass
class Device:
    """
    Element containing information about the measurement device from which the
    color values were derived.
    """

    class Meta:
        namespace = "http://colorexchangeformat.com/CxF3-core"

    manufacturer: str | None = field(
        default=None,
        metadata={
            "name": "Manufacturer",
            "type": "Element",
        },
    )
    model: str | None = field(
        default=None,
        metadata={
            "name": "Model",
            "type": "Element",
        },
    )
    serial_number: str | None = field(
        default=None,
        metadata={
            "name": "SerialNumber",
            "type": "Element",
        },
    )
    device_class: DeviceClass | None = field(
        default=None,
        metadata={
            "name": "DeviceClass",
            "type": "Element",
        },
    )
    device_filter: DeviceFilter | None = field(
        default=None,
        metadata={
            "name": "DeviceFilter",
            "type": "Element",
        },
    )
    device_illumination: DeviceIllumination | None = field(
        default=None,
        metadata={
            "name": "DeviceIllumination",
            "type": "Element",
        },
    )
    device_polarization: bool | None = field(
        default=None,
        metadata={
            "name": "DevicePolarization",
            "type": "Element",
        },
    )
